In [7]:
import torch 
import time
import numpy as np

In [4]:
randint = torch.randint(-100, 100, (20,))
randint

tensor([-24, -28, -46, -73,   2, -67, -98,  85,  -5,  32,  51, -78,  90,  64,
        -73, -63, -91, -94,  26, -82])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(10,10)
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
arange = torch.arange(100)
arange

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
linespace = torch.linspace(5, 20, steps=10)
linespace

tensor([ 5.0000,  6.6667,  8.3333, 10.0000, 11.6667, 13.3333, 15.0000, 16.6667,
        18.3333, 20.0000])

In [13]:
logspace = torch.logspace( start=-10, end=10, steps=100 )
logspace

tensor([1.0000e-10, 1.5923e-10, 2.5354e-10, 4.0370e-10, 6.4281e-10, 1.0235e-09,
        1.6298e-09, 2.5950e-09, 4.1320e-09, 6.5793e-09, 1.0476e-08, 1.6681e-08,
        2.6561e-08, 4.2292e-08, 6.7342e-08, 1.0723e-07, 1.7074e-07, 2.7186e-07,
        4.3288e-07, 6.8926e-07, 1.0975e-06, 1.7475e-06, 2.7826e-06, 4.4306e-06,
        7.0548e-06, 1.1233e-05, 1.7886e-05, 2.8480e-05, 4.5349e-05, 7.2208e-05,
        1.1498e-04, 1.8307e-04, 2.9151e-04, 4.6416e-04, 7.3907e-04, 1.1768e-03,
        1.8738e-03, 2.9836e-03, 4.7508e-03, 7.5646e-03, 1.2045e-02, 1.9179e-02,
        3.0539e-02, 4.8626e-02, 7.7426e-02, 1.2328e-01, 1.9630e-01, 3.1257e-01,
        4.9770e-01, 7.9248e-01, 1.2619e+00, 2.0092e+00, 3.1993e+00, 5.0941e+00,
        8.1113e+00, 1.2915e+01, 2.0565e+01, 3.2745e+01, 5.2140e+01, 8.3022e+01,
        1.3219e+02, 2.1049e+02, 3.3516e+02, 5.3367e+02, 8.4975e+02, 1.3530e+03,
        2.1544e+03, 3.4305e+03, 5.4623e+03, 8.6975e+03, 1.3849e+04, 2.2051e+04,
        3.5112e+04, 5.5908e+04, 8.9022e+

In [19]:
eye = torch.eye( 500 )
eye

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [17]:
a = torch.empty( (5,3), dtype=torch.int64 )
empty_like = torch.empty_like(a)
empty_like

tensor([[ 94593452256368, 139931255151840,              64],
        [             80,  94614379515287,               0],
        [              0,               0,               0],
        [              0,               0,               1],
        [              0,              97, 139931255151920]])

In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' 

torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'elapsed time: {elapsed_time:.8f}')

start_time = time.time()

rand = np



elapsed time: 2.20012522
